### ISSUE TITLE
Usage!?

### ISSUE THREAD

**Issue by Kasemfatani** [AbdallaMohammed/laravel-urway#1]
could you show us how to use it

**Comment by AbdallaMohammed** [comment]
I'm going to update the package and the documentation today and I will mention you

**Comment by AbdallaMohammed** [comment]
thank you for your waiting I updated the package and the docs hope it helped

[https://github.com/AbdallaMohammed/laravel-urway/releases/tag/1.1.0](v1.1.0)

**Comment by AbdallaMohammed** [comment]
Thank you for your waiting, now the package is updated.

[v1.1.0](https://github.com/AbdallaMohammed/laravel-urway/releases/tag/1.1.0)
