### ISSUE TITLE
issue after using setAttributes function

### ISSUE THREAD

**Issue by canaryDev41** [AbdallaMohammed/laravel-urway#2]
setAttributes() replaced the old array attributes and set the new one.

```

 /**
    * @return $this
*/
 public function setAttributes(array $attributes)
{
      $this->attributes = $attributes;
      return $this;
}

```

it should append the new attributes in the array not replace them.

**Comment by AbdallaMohammed** [comment]
Thank you for reporting this bug, I fixed that and I created new methods I hope those methods help you in your upcoming project. Have a nice day!

[v1.2.0](https://github.com/AbdallaMohammed/laravel-urway/releases/tag/1.2.0)

**Comment by canaryDev41** [comment]
Thanks for the effort, appreciated bro 💯
